### ISSUE TITLE
Stack install failing

### ISSUE THREAD

**Issue by vimuel** [bsl/bindings-GLFW#52]
Bindings-GLFW won't compile on my macOS 10.11.6: `fatal error: OpenGL/gl.h: No such file or directory`

Any ideas how I can resolve this issue?

Context:

```
$ stack install bindings-GLFW
Warning: File listed in .stack-work/downloaded/0pCfpnxANlB-/freetype2.cabal file does not exist: objs/ftmodule.h
Warning: File listed in .stack-work/downloaded/F_GRW2V-q8oW/nodejs-exec.cabal file does not exist: node/node
WARNING: Ignoring out of range dependency (allow-newer enabled): template-haskell-2.12.0.0. bindings-GLFW requires: >=2.10 && <2.12
bindings-GLFW-3.1.2.2: configure
bindings-GLFW-3.1.2.2: build

--  While building package bindings-GLFW-3.1.2.2 using:
      /Users/vilem/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.0.0.2_ghc-8.2.1 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.0.0.2 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/vilem/code/github/lamdu/.stack-work/logs/bindings-GLFW-3.1.2.2.log

    Configuring bindings-GLFW-3.1.2.2...
    Preprocessing library for bindings-GLFW-3.1.2.2..
    In file included from GLFW.hsc:9:0:
    /private/var/folders/12/1kppc1y16nzfg7ntgz9pyvfc0000gn/T/stack15987/bindings-GLFW-3.1.2.2/glfw/include/GLFW/glfw3.h:156:25: fatal error: OpenGL/gl.h: No such file or directory
    compilation terminated.
    compiling .stack-work/dist/x86_64-osx/Cabal-2.0.0.2/build/Bindings/GLFW_hsc_make.c failed (exit code 1)
```

**Comment by vimuel** [comment]
BTW, also tried cloning and installing from master, but I get the same issue:

```
$ stack install
[1 of 2] Compiling Main             ( /Users/vilem/.stack/setup-exe-src/setup-mPHDZzAJ.hs, /Users/vilem/.stack/setup-exe-src/setup-mPHDZzAJ.o )
[2 of 2] Compiling StackSetupShim   ( /Users/vilem/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /Users/vilem/.stack/setup-exe-src/setup-shim-mPHDZzAJ.o )
Linking /Users/vilem/.stack/setup-exe-cache/x86_64-osx/tmp-Cabal-simple_mPHDZzAJ_1.22.4.0_ghc-7.10.2 ...
bindings-DSL-1.0.22: download
bindings-DSL-1.0.22: configure
bindings-DSL-1.0.22: build
bindings-DSL-1.0.22: copy/register
bindings-GLFW-3.1.2.2: configure (lib)
Configuring bindings-GLFW-3.1.2.2...
bindings-GLFW-3.1.2.2: build (lib)
Preprocessing library bindings-GLFW-3.1.2.2...
In file included from GLFW.hsc:9:0:
/Users/vilem/code/github/bindings-GLFW/glfw/include/GLFW/glfw3.h:156:25: fatal error: OpenGL/gl.h: No such file or directory
compilation terminated.
compiling .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/Bindings/GLFW_hsc_make.c failed (exit code 1)
```

**Comment by yairchu** [comment]
Do you have the "Xcode command line tools" installed? (`xcode-select --install`)

**Comment by vimuel** [comment]
Yup.

**Comment by vimuel** [comment]
I even tried updating Xcode.

**Comment by yairchu** [comment]
Hmm.. What about [glfw](https://github.com/glfw/glfw)? Do its examples successfully build on your machine?

**Comment by vimuel** [comment]
Yes.
<img width="752" alt="screen shot 2017-08-31 at 18 03 20" src="https://user-images.githubusercontent.com/17603372/29935729-b6a2f030-8e77-11e7-826d-54c6940fb8cb.png">

**Comment by yairchu** [comment]
Hmm, what's version of stack do you have installed?

**Comment by vimuel** [comment]
I had Stack 1.4.0, but upgraded to 1.5.1 now but it still won't install:

```
$ stack install
--  While building package digest-0.0.1.2 using:
      /Users/vilem/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.0.0.2_ghc-8.2.1 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.0.0.2 configure --with-ghc=/Users/vilem/.stack/programs/x86_64-osx/ghc-8.2.1/bin/ghc --with-ghc-pkg=/Users/vilem/.stack/programs/x86_64-osx/ghc-8.2.1/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/Users/vilem/.stack/snapshots/x86_64-osx/nightly-2017-08-10/8.2.1/pkgdb --libdir=/Users/vilem/.stack/snapshots/x86_64-osx/nightly-2017-08-10/8.2.1/lib --bindir=/Users/vilem/.stack/snapshots/x86_64-osx/nightly-2017-08-10/8.2.1/bin --datadir=/Users/vilem/.stack/snapshots/x86_64-osx/nightly-2017-08-10/8.2.1/share --libexecdir=/Users/vilem/.stack/snapshots/x86_64-osx/nightly-2017-08-10/8.2.1/libexec --sysconfdir=/Users/vilem/.stack/snapshots/x86_64-osx/nightly-2017-08-10/8.2.1/etc --docdir=/Users/vilem/.stack/snapshots/x86_64-osx/nightly-2017-08-10/8.2.1/doc/digest-0.0.1.2 --htmldir=/Users/vilem/.stack/snapshots/x86_64-osx/nightly-2017-08-10/8.2.1/doc/digest-0.0.1.2 --haddockdir=/Users/vilem/.stack/snapshots/x86_64-osx/nightly-2017-08-10/8.2.1/doc/digest-0.0.1.2 --dependency=base=base-4.10.0.0 --dependency=bytestring=bytestring-0.10.8.2 -f-bytestring-in-base --exact-configuration
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/vilem/code/github/lamdu/.stack-work/logs/digest-0.0.1.2.log

    Configuring digest-0.0.1.2...
    Cabal-simple_mPHDZzAJ_2.0.0.2_ghc-8.2.1: Missing dependency on a foreign
    library:
    * Missing (or bad) header file: zlib.h
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
    If the header file does exist, it may contain errors that are caught by the C
    compiler at the preprocessing stage. In this case you can re-run configure
    with the verbosity flag -v3 to see the error messages.


--  While building package bindings-GLFW-3.1.2.2 using:
      /Users/vilem/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.0.0.2_ghc-8.2.1 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.0.0.2 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/vilem/code/github/lamdu/.stack-work/logs/bindings-GLFW-3.1.2.2.log

    Configuring bindings-GLFW-3.1.2.2...
    Preprocessing library for bindings-GLFW-3.1.2.2..
    /private/var/folders/12/1kppc1y16nzfg7ntgz9pyvfc0000gn/T/stack5873/bindings-GLFW-3.1.2.2/In file included from GLFW.hsc:9:0:
    /private/var/folders/12/1kppc1y16nzfg7ntgz9pyvfc0000gn/T/stack5873/bindings-GLFW-3.1.2.2/glfw/include/GLFW/glfw3.h:156:25: fatal error: OpenGL/gl.h: No such file or directory
    compilation terminated.
    compiling .stack-work/dist/x86_64-osx/Cabal-2.0.0.2/build/Bindings/GLFW_hsc_make.c failed (exit code 1)
    command was: /Users/vilem/.nix-profile/bin/gcc -c .stack-work/dist/x86_64-osx/Cabal-2.0.0.2/build/Bindings/GLFW_hsc_make.c -o .stack-work/dist/x86_64-osx/Cabal-2.0.0.2/build/Bindings/GLFW_hsc_make.o -m64 -fno-stack-protector -m64 -fno-stack-protector -m64 -D__GLASGOW_HASKELL__=802 -Ddarwin_BUILD_OS=1 -Dx86_64_BUILD_ARCH=1 -Ddarwin_HOST_OS=1 -Dx86_64_HOST_ARCH=1 -Iglfw/include/GLFW -Iglfw/include/ -Iglfw/src -Iglfw/include/os/darwin -D_GLFW_USE_CONFIG_H -I.stack-work/dist/x86_64-osx/Cabal-2.0.0.2/build/autogen -I.stack-work/dist/x86_64-osx/Cabal-2.0.0.2/build/global-autogen -include .stack-work/dist/x86_64-osx/Cabal-2.0.0.2/build/autogen/cabal_macros.h -I/Users/vilem/.stack/snapshots/x86_64-osx/nightly-2017-08-10/8.2.1/lib/x86_64-osx-ghc-8.2.1/bindings-DSL-1.0.23-GnirsnGaJOzLEFMHVhMFIe/include -I/Users/vilem/.stack/programs/x86_64-osx/ghc-8.2.1/lib/ghc-8.2.1/base-4.10.0.0/include -I/Users/vilem/.stack/programs/x86_64-osx/ghc-8.2.1/lib/ghc-8.2.1/integer-gmp-1.0.1.0/include -I/Users/vilem/.stack/programs/x86_64-osx/ghc-8.2.1/lib/ghc-8.2.1/include -I/Users/vilem/.stack/programs/x86_64-osx/ghc-8.2.1/lib/ghc-8.2.1/include/
```

BTW, I got it running fine on a friend's mac, but I did install *everything* from scratch (it didn't even have `brew`). Some state is messed up somewhere. Maybe I should consider a clean install of my OS? 😭

**Comment by yairchu** [comment]
Maybe `brew doctor` could notice something wrong? I'd further investigate why the `digest` package doesn't build because that seems like a smaller scope of problems which affect more people..

**Comment by Mokosha** [comment]
I've been working on OS X for a while without problems. I'm going to close this. If the problem persists feel free to reopen with additional details.

**Comment by vimuel** [comment]
Apologies I had forgotten about this. Thanks for closing.
