### ISSUE TITLE
bindings-GLFW-3.1 cannot find glfw_config.h

### ISSUE THREAD

**Issue by peti** [bsl/bindings-GLFW#20]
See http://hydra.cryp.to/build/606899/log/raw for a complete build log that shows the error.

**Comment by schell** [comment]
Well the warning 
    
    Warning: 'include-dirs: glfw/include/os/unix-like' directory does not exist.

definitely seems worrisome.

**Comment by schell** [comment]
@peti can you make sure that directory is included? It should be, I don't know how it couldn't but glfw_config.h lives in that dir so I'm sure that whatever caused the above warning is causing the error.

**Comment by schell** [comment]
It looks like `cabal sdist` didn't pick up the glfw/include/os dir.

**Comment by schell** [comment]
I don't know how but it looks like I had clobbered some includes in the cabal file. I've updated the repo and hackage. Please try building again :)

**Comment by peti** [comment]
Now I've run into this error:
    [1 of 1] Compiling Bindings.GLFW    ( dist/build/Bindings/GLFW.hs, dist/build/Bindings/GLFW.o )

    In file included from glfw/src/internal.h:74:0:
        0,
                         from glfw/src/context.c:28:

    glfw/src/x11_platform.h:38:33:
         fatal error: X11/Xcursor/Xcursor.h: No such file or directory
         #include <X11/Xcursor/Xcursor.h>

It appears the package has an undeclared dependency in `libXcursor`?

**Comment by peti** [comment]
The next error after that one is:

    glfw/src/x11_platform.h:53:37:
         fatal error: X11/extensions/Xinerama.h: No such file or directory
         #include <X11/extensions/Xinerama.h>

**Comment by schell** [comment]
This seems like it may be related to #14. I'm guessing we're missing some linked libs in the cabal file?

**Comment by peti** [comment]
Yes, `libXcursor` and `libXinerama` at least.

**Comment by schell** [comment]
I'm installing on an Ubuntu VM just fine, so I think this is a nix issue. @peti - can you add those libs to the cabal file and see if that gets you past these errors?

**Comment by peti** [comment]
After 9411a50, I get the following error:

    Configuring bindings-GLFW-3.1...
    Building bindings-GLFW-3.1...
    Preprocessing library bindings-GLFW-3.1...
    <command line>: does not exist: glfw/src/x11_gamma.c

Apparently, the file is listed in the Cabal file but missing from the repository?

Also, I notice that `cabal check` complains:

    $ cabal check
    These warnings may cause trouble when distributing the package:
    * 'ghc-options: -O2' is rarely needed. Check that it is giving a real benefit
    and not just imposing longer compile times on your users.

    The following errors will cause portability problems on other environments:
    * Unknown architecture name 'powerpc'

    Hackage would reject this package.

**Comment by peti** [comment]
See https://github.com/bsl/bindings-GLFW/pull/21.

**Comment by peti** [comment]
Even with that pull request applied, there remains an issue linking the test suite, though:

    Linking dist/build/main/main ...
    /tmp/nix-build-haskell-bindings-GLFW-3.1.drv-0/bindings-GLFW/dist/build/libHSbindings-GLFW-3.1-ghc7.8.4.so: undefined reference to `_glfwSetCurrentContext'
    /tmp/nix-build-haskell-bindings-GLFW-3.1.drv-0/bindings-GLFW/dist/build/libHSbindings-GLFW-3.1-ghc7.8.4.so: undefined reference to `_glfwTerminateTLS'
    /tmp/nix-build-haskell-bindings-GLFW-3.1.drv-0/bindings-GLFW/dist/build/libHSbindings-GLFW-3.1-ghc7.8.4.so: undefined reference to `_glfwPlatformGetCurrentContext'
    /tmp/nix-build-haskell-bindings-GLFW-3.1.drv-0/bindings-GLFW/dist/build/libHSbindings-GLFW-3.1-ghc7.8.4.so: undefined reference to `_glfwKeySym2Unicode'
    /tmp/nix-build-haskell-bindings-GLFW-3.1.drv-0/bindings-GLFW/dist/build/libHSbindings-GLFW-3.1-ghc7.8.4.so: undefined reference to `_glfwInitTLS'
    collect2: error: ld returned 1 exit status

I'm not sure what those symbols mean and who is supposed to provide them?

**Comment by klao** [comment]
The linking issues are due to a couple of C files (from the glfw source) not mentioned in the cabal file.

Here's a patch that gets the library and the test to successfully build on linux (Ubuntu 14.04):

```
diff -ur bindings-GLFW-3.1.1/bindings-GLFW.cabal bindings-GLFW-3.1.1.fix/bindings-GLFW.cabal
--- bindings-GLFW-3.1.1/bindings-GLFW.cabal     2015-03-09 16:50:00.688138179 +0100
+++ bindings-GLFW-3.1.1.fix/bindings-GLFW.cabal 2015-03-09 16:36:42.456173831 +0100
@@ -105,15 +105,19 @@
       glfw/src/x11_init.c
       glfw/src/x11_monitor.c
       glfw/src/x11_window.c
+      glfw/src/xkb_unicode.c
       glfw/src/glx_context.c
       glfw/src/linux_joystick.c
       glfw/src/posix_time.c
+      glfw/src/posix_tls.c
     extra-libraries:
       GL
       X11
       Xi
       Xrandr
       Xxf86vm
+      Xcursor
+      Xinerama
       pthread
 
   if os(darwin)
```

Sorry, can't send a pull request, because the repo is out-of-date. :)

Also note, that this only gets the tests to build. Some tests are still failing afterwards.

**Comment by schell** [comment]
Some of these changes were on my own fork as I had forgotten to `git push upstream master`. I've since set bsl/bindings-GLFW as `origin` so that won't happen again!
